### ISSUE TITLE
Question about parseScan method

### ISSUE THREAD

**Issue by soblenes32** [lessthanoptimal/jrplidar#2]
What is the intent of these checks in the RpLidarLowLevelDriver @ line 320 in the parseScan method? I'm trying to get this code working on the RPLidar A2, but the scan responses are always failing these two checks. It looks like it's validating something with the first two bytes of the packet: the start flag (0xA5) and the command byte (0x81) but I can't decipher why.

```
byte b0 = data[offset];
byte b1 = data[offset + 1];

boolean start0 = (b0 & 0x01) != 0;
boolean start1 = (b0 & 0x02) != 0;

if (start0 == start1)
return false;

if ((b1 & 0x01) != 1)
return false;
```

**Comment by jabrena** [comment]
Hi @soblenes32, I don't know if @lessthanoptimal has this model. In my case I use the first version without any problem. In few days, I will receive the `RPLidar A2` so I will help you in the process. Potentially, I am in the same case.

Juan Antonio

**Comment by lessthanoptimal** [comment]
yeah I just have an older model. I've been sitting on a pull request that might be related but haven't had a chance to test it out.

https://github.com/lessthanoptimal/jrplidar/pull/1

Is your issue and that pull request related?

**Comment by soblenes32** [comment]
I'm using code from that pull request to start up the motor and get the lidar spinning. Issuing a scan or express scan request alone isn't enough to get it moving. However, the routine that Redblade checked in should not impact the device's response messages. 

~~Could you possibly explain the logic behind the bitwise and operators in the code above? Is the purpose of this to discard the response descriptor message, or something else?~~

Edit: Ok, looking harder at the communication protocol spec I think I understand now. The purpose is to compare the start and inverse start flag at the offset 0 byte, per the table at the top of [page 15](http://www.robotshop.com/media/files/pdf2/rpk-02-communication-protocol.pdf).

**Comment by jabrena** [comment]
Hi @soblenes32, @lessthanoptimal, In one week, I will receive my A2 unit, I will test in both devices to maintain the compatibility. At the moment, I use A1 unit to publish data to `ROS`.

**Comment by jabrena** [comment]
Hi @soblenes32, 

Today, I have received the `RPLIDAR A2`. Tomorrow, I will check your PR.

Juan Antonio

**Comment by soblenes32** [comment]
By disabling some of the startup checks, and avoiding the autoSetCollectionToScan method, it seems to be working fine at about 2k samples/second. Resolving issue.

**Comment by jabrena** [comment]
Hi @soblenes32, 

do you have the class fixed to test in some place? I would like to review please. :)
